### ISSUE TITLE
css rem

### ISSUE THREAD

**Issue by MrWeilian** [MrWeilian/note-css#8]
> 关于rem

- rem是一种相对单位，直接相对于根元素的font-size。而一个文档的根元素就被认为是<html>。使用 rem 可以很方便的在各种屏幕尺寸下，通过等比缩放的方式达到设计图要求的效果。这样，rem在移动端就有很强的应用性了。

- 当然，考虑到移动端的话，还需要注意像素比dpr的还原/viewport的设置。

##### 设置rem的方案

- 方案1 @media
```css
@media screen and (min-width: 320px) {html{font-size:50px;}}
@media screen and (min-width: 360px) {html{font-size:56.25px;}}
@media screen and (min-width: 375px) {html{font-size:58.59375px;}}
@media screen and (min-width: 400px) {html{font-size:62.5px;}}
@media screen and (min-width: 414px) {html{font-size:64.6875px;}}
@media screen and (min-width: 440px) {html{font-size:68.75px;}}
@media screen and (min-width: 480px) {html{font-size:75px;}}
@media screen and (min-width: 520px) {html{font-size:81.25px;}}
@media screen and (min-width: 560px) {html{font-size:87.5px;}}
@media screen and (min-width: 600px) {html{font-size:93.75px;}}
@media screen and (min-width: 640px) {html{font-size:100px;}}
@media screen and (min-width: 680px) {html{font-size:106.25px;}}
@media screen and (min-width: 720px) {html{font-size:112.5px;}}
@media screen and (min-width: 760px) {html{font-size:118.75px;}}
@media screen and (min-width: 800px) {html{font-size:125px;}}
@media screen and (min-width: 960px) {html{font-size:150px;}}
```

- 方案2 js动态设置
```javascript
var html= document.getElementsByTagName("html")[0];
var clientWidth = html.getBoundingClientRect().width;
html.style.fontSize = clientWidth / 16 + "px"; //16是一个自定义数
```
以上js基于320px宽度的移动端设备开发。320/16=20px，既1rem=20px；
